// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// Hand-patched: putannouncement takes content as the raw body with ids in the
// query string (see buzz_rawput.go). Mirrors files put.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newAnnouncementsPutCmd(flags *rootFlags) *cobra.Command {
	var pEntityid, pPath string
	var filePath, contentType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "put",
		Short:       "This command posts an announcement to the domain or course specified by entityid .",
		Example:     "  agilix-buzz-pp-cli announcements put --entityid 123 --path guid.zip --file ann.zip",
		Annotations: map[string]string{"pp:endpoint": "announcements.put", "pp:method": "POST", "pp:path": "/cmd?cmd=putannouncement"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if pEntityid == "" || pPath == "" {
				_ = cmd.Usage()
				return usageErr(fmt.Errorf("--entityid and --path are required"))
			}
			params := map[string]string{}
			putParam(params, "entityid", pEntityid)
			putParam(params, "path", pPath)
			return runRawContentPut(cmd, flags, "announcements", "/cmd?cmd=putannouncement", params, filePath, stdinBody, contentType)
		},
	}
	cmd.Flags().StringVar(&pEntityid, "entityid", "", "ID of the domain or course to post to (required)")
	cmd.Flags().StringVar(&pPath, "path", "", "Unique path to the announcement file, e.g. guid.zip (required)")
	cmd.Flags().StringVar(&filePath, "file", "", "Local file whose bytes are uploaded as the announcement content")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read raw announcement content from stdin")
	cmd.Flags().StringVar(&contentType, "contenttype", "", "Content-Type of the body (application/json, text/xml, or application/zip)")

	return cmd
}
