// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAnnouncementsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "announcements",
		Short:       "List, get, create, and update announcements",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAnnouncementsGetCmd(flags))
	cmd.AddCommand(newAnnouncementsGetInfoCmd(flags))
	cmd.AddCommand(newAnnouncementsGetListCmd(flags))
	cmd.AddCommand(newAnnouncementsGetUserListCmd(flags))
	cmd.AddCommand(newAnnouncementsListRestorableCmd(flags))
	cmd.AddCommand(newAnnouncementsPutCmd(flags))
	cmd.AddCommand(newAnnouncementsRestoreCmd(flags))
	cmd.AddCommand(newAnnouncementsUpdateViewedCmd(flags))
	return cmd
}
