// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAssessmentsGetAttemptCmd(flags *rootFlags) *cobra.Command {
	var flagEnrollmentid string
	var flagItemid string
	var flagGroupid string
	var flagQuestionid string
	var flagPassword string
	var flagUtcoffset int

	cmd := &cobra.Command{
		Use:         "get-attempt",
		Short:       "This command returns the data needed for an assessment or homework attempt.",
		Example:     "  agilix-buzz-pp-cli assessments get-attempt",
		Annotations: map[string]string{"pp:endpoint": "assessments.get-attempt", "pp:method": "GET", "pp:path": "/cmd?cmd=getattempt", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/cmd?cmd=getattempt"
			params := map[string]string{}
			if flagEnrollmentid != "" {
				params["enrollmentid"] = formatCLIParamValue(flagEnrollmentid)
			}
			if flagItemid != "" {
				params["itemid"] = formatCLIParamValue(flagItemid)
			}
			if flagGroupid != "" {
				params["groupid"] = formatCLIParamValue(flagGroupid)
			}
			if flagQuestionid != "" {
				params["questionid"] = formatCLIParamValue(flagQuestionid)
			}
			if flagPassword != "" {
				params["password"] = formatCLIParamValue(flagPassword)
			}
			if flagUtcoffset != 0 {
				params["utcoffset"] = formatCLIParamValue(flagUtcoffset)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "assessments", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagEnrollmentid, "enrollmentid", "", "")
	cmd.Flags().StringVar(&flagItemid, "itemid", "", "")
	cmd.Flags().StringVar(&flagGroupid, "groupid", "", "")
	cmd.Flags().StringVar(&flagQuestionid, "questionid", "", "")
	cmd.Flags().StringVar(&flagPassword, "password", "", "")
	cmd.Flags().IntVar(&flagUtcoffset, "utcoffset", 0, "")

	return cmd
}
