// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAssessmentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "assessments",
		Short:       "Agilix Buzz assessments commands",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAssessmentsGetAttemptCmd(flags))
	cmd.AddCommand(newAssessmentsGetAttemptFileCmd(flags))
	cmd.AddCommand(newAssessmentsGetAttemptReviewCmd(flags))
	cmd.AddCommand(newAssessmentsGetNextQuestionCmd(flags))
	cmd.AddCommand(newAssessmentsGetQuestionCmd(flags))
	cmd.AddCommand(newAssessmentsGetQuestionScoresCmd(flags))
	cmd.AddCommand(newAssessmentsGetQuestionStatsCmd(flags))
	cmd.AddCommand(newAssessmentsGetSubmissionStateCmd(flags))
	cmd.AddCommand(newAssessmentsListQuestionsCmd(flags))
	cmd.AddCommand(newAssessmentsListRestorableQuestionsCmd(flags))
	cmd.AddCommand(newAssessmentsPutAttemptFileCmd(flags))
	cmd.AddCommand(newAssessmentsPutQuestionsCmd(flags))
	cmd.AddCommand(newAssessmentsRestoreQuestionsCmd(flags))
	cmd.AddCommand(newAssessmentsSaveAttemptAnswersCmd(flags))
	cmd.AddCommand(newAssessmentsSubmitAttemptAnswersCmd(flags))
	return cmd
}
