// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// Hand-patched: putattemptfile takes the file as the raw body with ids in the
// query string (see buzz_rawput.go). Mirrors files put.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newAssessmentsPutAttemptFileCmd(flags *rootFlags) *cobra.Command {
	var pEnrollmentid, pItemid, pPartid string
	var filePath, contentType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "put-attempt-file",
		Short:       "This command puts files on the server to be associated with a fileupload question as part of a student",
		Example:     "  agilix-buzz-pp-cli assessments put-attempt-file --enrollmentid 123 --itemid abc --partid 1 --file upload.pdf",
		Annotations: map[string]string{"pp:endpoint": "assessments.put-attempt-file", "pp:method": "POST", "pp:path": "/cmd?cmd=putattemptfile"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if pEnrollmentid == "" || pItemid == "" {
				_ = cmd.Usage()
				return usageErr(fmt.Errorf("--enrollmentid and --itemid are required"))
			}
			params := map[string]string{}
			putParam(params, "enrollmentid", pEnrollmentid)
			putParam(params, "itemid", pItemid)
			putParam(params, "partid", pPartid)
			return runRawContentPut(cmd, flags, "assessments", "/cmd?cmd=putattemptfile", params, filePath, stdinBody, contentType)
		},
	}
	cmd.Flags().StringVar(&pEnrollmentid, "enrollmentid", "", "Student enrollment (required)")
	cmd.Flags().StringVar(&pItemid, "itemid", "", "Assessment item ID (required)")
	cmd.Flags().StringVar(&pPartid, "partid", "", "Question/part ID the file is associated with")
	cmd.Flags().StringVar(&filePath, "file", "", "Local file whose bytes are uploaded")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read raw file content from stdin")
	cmd.Flags().StringVar(&contentType, "contenttype", "", "Content-Type of the uploaded file")

	return cmd
}
