// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBadgesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "badges",
		Short:       "Get and create badges",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBadgesCreateCmd(flags))
	cmd.AddCommand(newBadgesGetCmd(flags))
	cmd.AddCommand(newBadgesGetAssertionCmd(flags))
	cmd.AddCommand(newBadgesGetListCmd(flags))
	return cmd
}
