// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// Hand-patched: putblog takes content as the raw body with ids in the query
// string (see buzz_rawput.go). Mirrors files put.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newBlogsPutCmd(flags *rootFlags) *cobra.Command {
	var pEnrollmentid, pItemid, pMessageid, pParentid, pAuthorid string
	var filePath, contentType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "put",
		Short:       "This command puts a blog or journal message to the server.",
		Example:     "  agilix-buzz-pp-cli blogs put --enrollmentid 123 --itemid abc --file post.json",
		Annotations: map[string]string{"pp:endpoint": "blogs.put", "pp:method": "POST", "pp:path": "/cmd?cmd=putblog"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if pEnrollmentid == "" || pItemid == "" {
				_ = cmd.Usage()
				return usageErr(fmt.Errorf("--enrollmentid and --itemid are required"))
			}
			params := map[string]string{}
			putParam(params, "enrollmentid", pEnrollmentid)
			putParam(params, "itemid", pItemid)
			putParam(params, "messageid", pMessageid)
			putParam(params, "parentid", pParentid)
			putParam(params, "authorid", pAuthorid)
			return runRawContentPut(cmd, flags, "blogs", "/cmd?cmd=putblog", params, filePath, stdinBody, contentType)
		},
	}
	cmd.Flags().StringVar(&pEnrollmentid, "enrollmentid", "", "Enrollment that owns the blog (required)")
	cmd.Flags().StringVar(&pItemid, "itemid", "", "Blog item ID (required)")
	cmd.Flags().StringVar(&pMessageid, "messageid", "", "Existing message ID to update")
	cmd.Flags().StringVar(&pParentid, "parentid", "", "Parent message ID for replies")
	cmd.Flags().StringVar(&pAuthorid, "authorid", "", "Author user ID")
	cmd.Flags().StringVar(&filePath, "file", "", "Local file whose bytes are uploaded as the message content")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read raw message content from stdin")
	cmd.Flags().StringVar(&contentType, "contenttype", "", "Content-Type of the body (application/json, text/xml, or application/zip)")

	return cmd
}
