// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBlogsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "blogs",
		Short:       "Get, create, and update blogs",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBlogsGetCmd(flags))
	cmd.AddCommand(newBlogsGetListCmd(flags))
	cmd.AddCommand(newBlogsGetRecentPostsCmd(flags))
	cmd.AddCommand(newBlogsGetSummaryCmd(flags))
	cmd.AddCommand(newBlogsPutCmd(flags))
	cmd.AddCommand(newBlogsUpdateViewedCmd(flags))
	return cmd
}
