// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newNovelClassCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:         "class",
		Short:       "class subcommands: engagement",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}
	cmd.AddCommand(newNovelClassEngagementCmd(flags))
	return cmd
}
