// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newConversionCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "conversion",
		Short:       "Get and create conversion",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newConversionExportDataCmd(flags))
	cmd.AddCommand(newConversionGetConvertedDataCmd(flags))
	cmd.AddCommand(newConversionImportDataCmd(flags))
	return cmd
}
