// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "courses",
		Short:       "Courses & course copy",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCoursesCopyCmd(flags))
	cmd.AddCommand(newCoursesCreateCmd(flags))
	cmd.AddCommand(newCoursesCreateDemoCmd(flags))
	cmd.AddCommand(newCoursesDeactivateCmd(flags))
	cmd.AddCommand(newCoursesGetCmd(flags))
	cmd.AddCommand(newCoursesListCmd(flags))
	cmd.AddCommand(newCoursesMergeCmd(flags))
	cmd.AddCommand(newCoursesRestoreCmd(flags))
	cmd.AddCommand(newCoursesUpdateCmd(flags))
	return cmd
}
