// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newDatastreamsSetDataStreamConfigurationCmd(flags *rootFlags) *cobra.Command {
	var bodyDomainid string
	var bodyTest string
	var bodyTitle string
	var bodyEnabled string
	var bodyTargetFirehoseStream string
	var bodyRoleArn string
	var bodyTargetRegion string
	var bodyEventType string
	var bodyProperties string
	var bodyTargetKinesisStream string
	var bodyStreamName string
	var bodyTimeoutSeconds string
	var bodyRetries string
	var bodyEndpoints string
	var bodyHttpMethod string
	var bodyTargetSqsQueue string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "set-data-stream-configuration",
		Short:       "This command tests a given data stream configuration to see if it is valid and if the API servers can connect to it and",
		Example:     "  agilix-buzz-pp-cli datastreams set-data-stream-configuration",
		Annotations: map[string]string{"pp:endpoint": "datastreams.set-data-stream-configuration", "pp:method": "POST", "pp:path": "/cmd?cmd=setdatastreamconfiguration"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/cmd?cmd=setdatastreamconfiguration"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyDomainid != "" {
					body["domainid"] = bodyDomainid
				}
				if bodyTest != "" {
					body["test"] = bodyTest
				}
				if bodyTitle != "" {
					body["title"] = bodyTitle
				}
				if bodyEnabled != "" {
					body["enabled"] = bodyEnabled
				}
				if bodyTargetFirehoseStream != "" {
					body["targetFirehoseStream"] = bodyTargetFirehoseStream
				}
				if bodyRoleArn != "" {
					body["roleArn"] = bodyRoleArn
				}
				if bodyTargetRegion != "" {
					body["targetRegion"] = bodyTargetRegion
				}
				if bodyEventType != "" {
					body["eventType"] = bodyEventType
				}
				if bodyProperties != "" {
					body["properties"] = bodyProperties
				}
				if bodyTargetKinesisStream != "" {
					body["targetKinesisStream"] = bodyTargetKinesisStream
				}
				if bodyStreamName != "" {
					body["streamName"] = bodyStreamName
				}
				if bodyTimeoutSeconds != "" {
					body["timeoutSeconds"] = bodyTimeoutSeconds
				}
				if bodyRetries != "" {
					body["retries"] = bodyRetries
				}
				if bodyEndpoints != "" {
					body["endpoints"] = bodyEndpoints
				}
				if bodyHttpMethod != "" {
					body["httpMethod"] = bodyHttpMethod
				}
				if bodyTargetSqsQueue != "" {
					body["targetSqsQueue"] = bodyTargetSqsQueue
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "datastreams", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "datastreams", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "datastreams", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "datastreams", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "datastreams", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "datastreams",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "datastreams", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "datastreams", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyDomainid, "domainid", "", "")
	cmd.Flags().StringVar(&bodyTest, "test", "", "")
	cmd.Flags().StringVar(&bodyTitle, "title", "", "")
	cmd.Flags().StringVar(&bodyEnabled, "enabled", "", "")
	cmd.Flags().StringVar(&bodyTargetFirehoseStream, "target-firehose-stream", "", "")
	cmd.Flags().StringVar(&bodyRoleArn, "role-arn", "", "")
	cmd.Flags().StringVar(&bodyTargetRegion, "target-region", "", "")
	cmd.Flags().StringVar(&bodyEventType, "event-type", "", "")
	cmd.Flags().StringVar(&bodyProperties, "properties", "", "")
	cmd.Flags().StringVar(&bodyTargetKinesisStream, "target-kinesis-stream", "", "")
	cmd.Flags().StringVar(&bodyStreamName, "stream-name", "", "")
	cmd.Flags().StringVar(&bodyTimeoutSeconds, "timeout-seconds", "", "")
	cmd.Flags().StringVar(&bodyRetries, "retries", "", "")
	cmd.Flags().StringVar(&bodyEndpoints, "endpoints", "", "")
	cmd.Flags().StringVar(&bodyHttpMethod, "http-method", "", "")
	cmd.Flags().StringVar(&bodyTargetSqsQueue, "target-sqs-queue", "", "")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
