// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDatastreamsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "datastreams",
		Short:       "Get and create datastreams",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDatastreamsGetDataStreamConfigurationCmd(flags))
	cmd.AddCommand(newDatastreamsSetDataStreamConfigurationCmd(flags))
	return cmd
}
