// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// Hand-patched: putmessage takes content as the raw body with ids in the query
// string (see buzz_rawput.go). Mirrors files put.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newDiscussionsPutMessageCmd(flags *rootFlags) *cobra.Command {
	var pEntityid, pItemid, pGroupid, pMessageid, pParentid, pStatus string
	var filePath, contentType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "put-message",
		Short:       "This command puts a discussion board message to the server.",
		Example:     "  agilix-buzz-pp-cli discussions put-message --entityid 123 --itemid abc --file message.zip",
		Annotations: map[string]string{"pp:endpoint": "discussions.put-message", "pp:method": "POST", "pp:path": "/cmd?cmd=putmessage"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if pEntityid == "" || pItemid == "" {
				_ = cmd.Usage()
				return usageErr(fmt.Errorf("--entityid and --itemid are required"))
			}
			params := map[string]string{}
			putParam(params, "entityid", pEntityid)
			putParam(params, "itemid", pItemid)
			putParam(params, "groupid", pGroupid)
			putParam(params, "messageid", pMessageid)
			putParam(params, "parentid", pParentid)
			putParam(params, "status", pStatus)
			return runRawContentPut(cmd, flags, "discussions", "/cmd?cmd=putmessage", params, filePath, stdinBody, contentType)
		},
	}
	cmd.Flags().StringVar(&pEntityid, "entityid", "", "Course/section that owns the forum (required)")
	cmd.Flags().StringVar(&pItemid, "itemid", "", "Forum item ID (required)")
	cmd.Flags().StringVar(&pGroupid, "groupid", "", "Group ID for group discussions")
	cmd.Flags().StringVar(&pMessageid, "messageid", "", "Existing message ID to update")
	cmd.Flags().StringVar(&pParentid, "parentid", "", "Parent message ID for replies")
	cmd.Flags().StringVar(&pStatus, "status", "", "Message status")
	cmd.Flags().StringVar(&filePath, "file", "", "Local file (zip) whose bytes are uploaded as the message")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read raw message content from stdin")
	cmd.Flags().StringVar(&contentType, "contenttype", "", "Content-Type of the body (default application/zip)")

	return cmd
}
