// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// Hand-patched: putmessagepart takes content as the raw body with ids in the
// query string (see buzz_rawput.go). Mirrors files put. Note: --filepath is the
// DLAP query param; --file is the local upload source.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newDiscussionsPutMessagePartCmd(flags *rootFlags) *cobra.Command {
	var pEntityid, pItemid, pMessageid, pGroupid, pFilepath, pDisposition, pSchema string
	var filePath, contentType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "put-message-part",
		Short:       "This command puts individual parts of a discussion board message to the server.",
		Example:     "  agilix-buzz-pp-cli discussions put-message-part --entityid 123 --itemid abc --filepath body.html --file body.html",
		Annotations: map[string]string{"pp:endpoint": "discussions.put-message-part", "pp:method": "POST", "pp:path": "/cmd?cmd=putmessagepart"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if pEntityid == "" || pItemid == "" {
				_ = cmd.Usage()
				return usageErr(fmt.Errorf("--entityid and --itemid are required"))
			}
			params := map[string]string{}
			putParam(params, "entityid", pEntityid)
			putParam(params, "itemid", pItemid)
			putParam(params, "messageid", pMessageid)
			putParam(params, "groupid", pGroupid)
			putParam(params, "filepath", pFilepath)
			putParam(params, "disposition", pDisposition)
			putParam(params, "schema", pSchema)
			return runRawContentPut(cmd, flags, "discussions", "/cmd?cmd=putmessagepart", params, filePath, stdinBody, contentType)
		},
	}
	cmd.Flags().StringVar(&pEntityid, "entityid", "", "Course/section that owns the forum (required)")
	cmd.Flags().StringVar(&pItemid, "itemid", "", "Forum item ID (required)")
	cmd.Flags().StringVar(&pMessageid, "messageid", "", "Message ID this part belongs to")
	cmd.Flags().StringVar(&pGroupid, "groupid", "", "Group ID for group discussions")
	cmd.Flags().StringVar(&pFilepath, "filepath", "", "Target path of the message part")
	cmd.Flags().StringVar(&pDisposition, "disposition", "", "Disposition for the upload")
	cmd.Flags().StringVar(&pSchema, "schema", "", "Schema for the message part")
	cmd.Flags().StringVar(&filePath, "file", "", "Local file whose bytes are uploaded as the part content")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read raw part content from stdin")
	cmd.Flags().StringVar(&contentType, "contenttype", "", "Content-Type of the uploaded content")

	return cmd
}
