// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDiscussionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "discussions",
		Short:       "List, get, create, update, and submit discussions",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDiscussionsGetMessageCmd(flags))
	cmd.AddCommand(newDiscussionsGetMessageListCmd(flags))
	cmd.AddCommand(newDiscussionsListRestorableMessagesCmd(flags))
	cmd.AddCommand(newDiscussionsPutMessageCmd(flags))
	cmd.AddCommand(newDiscussionsPutMessagePartCmd(flags))
	cmd.AddCommand(newDiscussionsRestoreMessagesCmd(flags))
	cmd.AddCommand(newDiscussionsSubmitMessageCmd(flags))
	cmd.AddCommand(newDiscussionsUpdateMessageViewedCmd(flags))
	return cmd
}
