// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDomainsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "domains",
		Short:       "Domains (schools/districts) & hierarchy",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDomainsCreateCmd(flags))
	cmd.AddCommand(newDomainsGetCmd(flags))
	cmd.AddCommand(newDomainsGetContentCmd(flags))
	cmd.AddCommand(newDomainsGetEnrollmentMetricsCmd(flags))
	cmd.AddCommand(newDomainsGetEnrollmentMetricsParametersCmd(flags))
	cmd.AddCommand(newDomainsGetParentListCmd(flags))
	cmd.AddCommand(newDomainsGetSettingsCmd(flags))
	cmd.AddCommand(newDomainsGetStatsCmd(flags))
	cmd.AddCommand(newDomainsListCmd(flags))
	cmd.AddCommand(newDomainsRestoreCmd(flags))
	cmd.AddCommand(newDomainsUpdateCmd(flags))
	return cmd
}
