// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEnrollmentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "enrollments",
		Short:       "Enrollments (user-course bindings) & activity",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEnrollmentsCreateCmd(flags))
	cmd.AddCommand(newEnrollmentsGetCmd(flags))
	cmd.AddCommand(newEnrollmentsGetActivityCmd(flags))
	cmd.AddCommand(newEnrollmentsGetGradebookCmd(flags))
	cmd.AddCommand(newEnrollmentsGetGroupListCmd(flags))
	cmd.AddCommand(newEnrollmentsGetMetricsReportCmd(flags))
	cmd.AddCommand(newEnrollmentsListCmd(flags))
	cmd.AddCommand(newEnrollmentsListByTeacherCmd(flags))
	cmd.AddCommand(newEnrollmentsListEntityCmd(flags))
	cmd.AddCommand(newEnrollmentsListUserCmd(flags))
	cmd.AddCommand(newEnrollmentsPutSelfAssessmentCmd(flags))
	cmd.AddCommand(newEnrollmentsRestoreCmd(flags))
	cmd.AddCommand(newEnrollmentsUpdateCmd(flags))
	return cmd
}
