// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newEnrollmentsListCmd(flags *rootFlags) *cobra.Command {
	var flagDomainid string
	var flagIncludedescendantdomains bool
	var flagLimit int
	var flagShow string
	var flagSelect string
	var flagQuery string
	var flagUserdomainid string
	var flagUserquery string
	var flagUsertext string
	var flagCoursedomainid string
	var flagCoursequery string
	var flagCoursetext string

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "This command lists enrollments.",
		Example:     "  agilix-buzz-pp-cli enrollments list",
		Annotations: map[string]string{"pp:endpoint": "enrollments.list", "pp:method": "GET", "pp:path": "/cmd?cmd=listenrollments", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/cmd?cmd=listenrollments"
			params := map[string]string{}
			if flagDomainid != "" {
				params["domainid"] = formatCLIParamValue(flagDomainid)
			}
			if flagIncludedescendantdomains != false {
				params["includedescendantdomains"] = formatCLIParamValue(flagIncludedescendantdomains)
			}
			if flagLimit != 0 {
				params["limit"] = formatCLIParamValue(flagLimit)
			}
			if flagShow != "" {
				params["show"] = formatCLIParamValue(flagShow)
			}
			if flagSelect != "" {
				params["select"] = formatCLIParamValue(flagSelect)
			}
			if flagQuery != "" {
				params["query"] = formatCLIParamValue(flagQuery)
			}
			if flagUserdomainid != "" {
				params["userdomainid"] = formatCLIParamValue(flagUserdomainid)
			}
			if flagUserquery != "" {
				params["userquery"] = formatCLIParamValue(flagUserquery)
			}
			if flagUsertext != "" {
				params["usertext"] = formatCLIParamValue(flagUsertext)
			}
			if flagCoursedomainid != "" {
				params["coursedomainid"] = formatCLIParamValue(flagCoursedomainid)
			}
			if flagCoursequery != "" {
				params["coursequery"] = formatCLIParamValue(flagCoursequery)
			}
			if flagCoursetext != "" {
				params["coursetext"] = formatCLIParamValue(flagCoursetext)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "enrollments", true, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Honor --limit when the API accepts but ignores ?limit=N.
			data = truncateJSONArray(data, flagLimit)
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagDomainid, "domainid", "", "")
	cmd.Flags().BoolVar(&flagIncludedescendantdomains, "includedescendantdomains", false, "")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "")
	cmd.Flags().StringVar(&flagShow, "show", "", "")
	cmd.Flags().StringVar(&flagSelect, "select", "", "")
	cmd.Flags().StringVar(&flagQuery, "query", "", "")
	cmd.Flags().StringVar(&flagUserdomainid, "userdomainid", "", "")
	cmd.Flags().StringVar(&flagUserquery, "userquery", "", "")
	cmd.Flags().StringVar(&flagUsertext, "usertext", "", "")
	cmd.Flags().StringVar(&flagCoursedomainid, "coursedomainid", "", "")
	cmd.Flags().StringVar(&flagCoursequery, "coursequery", "", "")
	cmd.Flags().StringVar(&flagCoursetext, "coursetext", "", "")

	return cmd
}
