// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFilesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "files",
		Short:       "Course resources & files",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFilesCopyCmd(flags))
	cmd.AddCommand(newFilesGetCmd(flags))
	cmd.AddCommand(newFilesGetDocumentCmd(flags))
	cmd.AddCommand(newFilesGetDocumentInfoCmd(flags))
	cmd.AddCommand(newFilesGetEntityIdCmd(flags))
	cmd.AddCommand(newFilesGetInfoCmd(flags))
	cmd.AddCommand(newFilesGetListCmd(flags))
	cmd.AddCommand(newFilesListRestorableCmd(flags))
	cmd.AddCommand(newFilesListRestorableDocumentsCmd(flags))
	cmd.AddCommand(newFilesPutCmd(flags))
	cmd.AddCommand(newFilesPutFoldersCmd(flags))
	cmd.AddCommand(newFilesRestoreCmd(flags))
	cmd.AddCommand(newFilesRestoreDocumentsCmd(flags))
	return cmd
}
