// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"mime"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

func newFilesPutCmd(flags *rootFlags) *cobra.Command {
	var bodyEntityid string
	var bodyPath string
	var bodyStatus string
	var bodyClass string
	var bodyDrophistory string
	var bodyContenttype string
	var filePath string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "put",
		Short:       "This command puts a resource to the server for the specified course, section, enrollment, user, or domain.",
		Example:     "  agilix-buzz-pp-cli files put",
		Annotations: map[string]string{"pp:endpoint": "files.put", "pp:method": "POST", "pp:path": "/cmd?cmd=putresource"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 && cmd.Flags().NFlag() == 0 {
				return cmd.Help()
			}
			// PutResource takes entityid/path (and status/class/etc) as
			// query-string parameters, and the resource CONTENT as the raw
			// request body — not a JSON body. Provide content via --file or --stdin.
			if bodyEntityid == "" || bodyPath == "" {
				_ = cmd.Usage()
				return usageErr(fmt.Errorf("--entityid and --path are required"))
			}
			if filePath == "" && !stdinBody {
				_ = cmd.Usage()
				return usageErr(fmt.Errorf("provide resource content via --file <path> or --stdin"))
			}
			path := "/cmd?cmd=putresource"
			if flags.dryRun {
				src := filePath
				if src == "" {
					src = "<stdin>"
				}
				fmt.Fprintf(cmd.OutOrStdout(), "would PUT resource from %s to entityid=%s path=%s\n", src, bodyEntityid, bodyPath)
				return nil
			}
			params := map[string]string{"entityid": bodyEntityid, "path": bodyPath}
			if bodyStatus != "" {
				params["status"] = bodyStatus
			}
			if bodyClass != "" {
				params["class"] = bodyClass
			}
			if bodyDrophistory != "" {
				params["drophistory"] = bodyDrophistory
			}
			ct := bodyContenttype
			var content []byte
			if filePath != "" {
				b, rerr := os.ReadFile(filePath) // #nosec G304 -- user-named upload file, opened locally; that is the command's purpose
				if rerr != nil {
					return fmt.Errorf("reading --file: %w", rerr)
				}
				content = b
				if ct == "" {
					ct = mime.TypeByExtension(filepath.Ext(filePath))
				}
			} else {
				b, rerr := io.ReadAll(os.Stdin)
				if rerr != nil {
					return fmt.Errorf("reading stdin: %w", rerr)
				}
				content = b
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, statusCode, err := c.PostRawResource(cmd.Context(), path, params, content, ct)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "files", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "files", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "files", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "files", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "files", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "files",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "files", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "files", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyEntityid, "entityid", "", "ID of the course/enrollment/domain that owns the resource (required)")
	cmd.Flags().StringVar(&bodyPath, "path", "", "Unique resource path, e.g. Templates/Data/page.html (required)")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "hidden to hide the resource from students")
	cmd.Flags().StringVar(&bodyClass, "class", "", "4-char resource class; MISC for arbitrary app resources")
	cmd.Flags().StringVar(&bodyDrophistory, "drophistory", "", "true to mark this as a temporary version")
	cmd.Flags().StringVar(&bodyContenttype, "contenttype", "", "Override Content-Type for the uploaded content")
	cmd.Flags().StringVar(&filePath, "file", "", "Local file whose bytes are uploaded as the resource content")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read raw resource content from stdin")

	return cmd
}
