// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGradebookCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "gradebook",
		Short:       "Gradebook results & grading",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGradebookCalculateEnrollmentScenarioCmd(flags))
	cmd.AddCommand(newGradebookGetCalendarCmd(flags))
	cmd.AddCommand(newGradebookGetCalendarItemsCmd(flags))
	cmd.AddCommand(newGradebookGetCalendarTokenCmd(flags))
	cmd.AddCommand(newGradebookGetCertificatesCmd(flags))
	cmd.AddCommand(newGradebookGetDueSoonListCmd(flags))
	cmd.AddCommand(newGradebookGetEntitySummaryCmd(flags))
	cmd.AddCommand(newGradebookGetEntityWorkCmd(flags))
	cmd.AddCommand(newGradebookGetGradeCmd(flags))
	cmd.AddCommand(newGradebookGetGradeHistoryCmd(flags))
	cmd.AddCommand(newGradebookGetItemAnalysisCmd(flags))
	cmd.AddCommand(newGradebookGetItemReportCmd(flags))
	cmd.AddCommand(newGradebookGetListCmd(flags))
	cmd.AddCommand(newGradebookGetRubricMasteryCmd(flags))
	cmd.AddCommand(newGradebookGetRubricStatsCmd(flags))
	cmd.AddCommand(newGradebookGetSummaryCmd(flags))
	cmd.AddCommand(newGradebookGetUserCmd(flags))
	cmd.AddCommand(newGradebookGetWeightsCmd(flags))
	cmd.AddCommand(newGradebookGetentitygradebook2Cmd(flags))
	cmd.AddCommand(newGradebookGetentitygradebook3Cmd(flags))
	cmd.AddCommand(newNovelGradebookStaleCmd(flags))
	return cmd
}
