// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGradebookGetentitygradebook2Cmd(flags *rootFlags) *cobra.Command {
	var flagEntityid string
	var flagAllstatus bool
	var flagForcerequireditems bool
	var flagDaysactivepastend int
	var flagGradingschemeid string
	var flagGradingscheme string
	var flagItemid string
	var flagScorm bool
	var flagSelect string
	var flagUserid string
	var flagZerounscored bool

	cmd := &cobra.Command{
		Use:         "getentitygradebook2",
		Short:       "This command gets grades for all students enrolled in the specified entity.",
		Example:     "  agilix-buzz-pp-cli gradebook getentitygradebook2",
		Annotations: map[string]string{"pp:endpoint": "gradebook.getentitygradebook2", "pp:method": "GET", "pp:path": "/cmd?cmd=getentitygradebook2", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/cmd?cmd=getentitygradebook2"
			params := map[string]string{}
			if flagEntityid != "" {
				params["entityid"] = formatCLIParamValue(flagEntityid)
			}
			if flagAllstatus != false {
				params["allstatus"] = formatCLIParamValue(flagAllstatus)
			}
			if flagForcerequireditems != false {
				params["forcerequireditems"] = formatCLIParamValue(flagForcerequireditems)
			}
			if flagDaysactivepastend != 0 {
				params["daysactivepastend"] = formatCLIParamValue(flagDaysactivepastend)
			}
			if flagGradingschemeid != "" {
				params["gradingschemeid"] = formatCLIParamValue(flagGradingschemeid)
			}
			if flagGradingscheme != "" {
				params["gradingscheme"] = formatCLIParamValue(flagGradingscheme)
			}
			if flagItemid != "" {
				params["itemid"] = formatCLIParamValue(flagItemid)
			}
			if flagScorm != false {
				params["scorm"] = formatCLIParamValue(flagScorm)
			}
			if flagSelect != "" {
				params["select"] = formatCLIParamValue(flagSelect)
			}
			if flagUserid != "" {
				params["userid"] = formatCLIParamValue(flagUserid)
			}
			if flagZerounscored != false {
				params["zerounscored"] = formatCLIParamValue(flagZerounscored)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "gradebook", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagEntityid, "entityid", "", "")
	cmd.Flags().BoolVar(&flagAllstatus, "allstatus", false, "")
	cmd.Flags().BoolVar(&flagForcerequireditems, "forcerequireditems", false, "")
	cmd.Flags().IntVar(&flagDaysactivepastend, "daysactivepastend", 0, "")
	cmd.Flags().StringVar(&flagGradingschemeid, "gradingschemeid", "", "")
	cmd.Flags().StringVar(&flagGradingscheme, "gradingscheme", "", "")
	cmd.Flags().StringVar(&flagItemid, "itemid", "", "")
	cmd.Flags().BoolVar(&flagScorm, "scorm", false, "")
	cmd.Flags().StringVar(&flagSelect, "select", "", "")
	cmd.Flags().StringVar(&flagUserid, "userid", "", "")
	cmd.Flags().BoolVar(&flagZerounscored, "zerounscored", false, "")

	return cmd
}
