// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "groups",
		Short:       "Get, create, add, update, and remove groups",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGroupsAddMembersCmd(flags))
	cmd.AddCommand(newGroupsCreateCmd(flags))
	cmd.AddCommand(newGroupsGetCmd(flags))
	cmd.AddCommand(newGroupsGetEnrollmentListCmd(flags))
	cmd.AddCommand(newGroupsGetListCmd(flags))
	cmd.AddCommand(newGroupsRemoveMembersCmd(flags))
	cmd.AddCommand(newGroupsUpdateCmd(flags))
	return cmd
}
