// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newItemsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "items",
		Short:       "Manifests & content items",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newItemsAssignCmd(flags))
	cmd.AddCommand(newItemsCopyCmd(flags))
	cmd.AddCommand(newItemsFindPersonalizedEntitiesCmd(flags))
	cmd.AddCommand(newItemsGetDataCmd(flags))
	cmd.AddCommand(newItemsGetLinksCmd(flags))
	cmd.AddCommand(newItemsGetListCmd(flags))
	cmd.AddCommand(newItemsGetitemCmd(flags))
	cmd.AddCommand(newItemsGetiteminfoCmd(flags))
	cmd.AddCommand(newItemsGetmanifestCmd(flags))
	cmd.AddCommand(newItemsGetmanifestinfoCmd(flags))
	cmd.AddCommand(newItemsGetmanifestitemCmd(flags))
	cmd.AddCommand(newItemsListAssignableCmd(flags))
	cmd.AddCommand(newItemsListRestorableCmd(flags))
	cmd.AddCommand(newItemsNavigateCmd(flags))
	cmd.AddCommand(newItemsPutCmd(flags))
	cmd.AddCommand(newItemsRestoreCmd(flags))
	cmd.AddCommand(newItemsSearchCmd(flags))
	cmd.AddCommand(newItemsUnassignCmd(flags))
	cmd.AddCommand(newItemsUpdateDataCmd(flags))
	return cmd
}
