// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newItemsSearchCmd(flags *rootFlags) *cobra.Command {
	var flagEntityid string
	var flagOmitentityid string
	var flagItemtype string
	var flagSubscriptions string
	var flagQuery string
	var flagLimit int
	var flagStart string

	cmd := &cobra.Command{
		Use:         "search",
		Short:       "This command searches course content that has been marked by course creators as searchable and returns a paginated list",
		Example:     "  agilix-buzz-pp-cli items search",
		Annotations: map[string]string{"pp:endpoint": "items.search", "pp:method": "GET", "pp:path": "/cmd?cmd=search2", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/cmd?cmd=search2"
			params := map[string]string{}
			if flagEntityid != "" {
				params["entityid"] = formatCLIParamValue(flagEntityid)
			}
			if flagOmitentityid != "" {
				params["omitentityid"] = formatCLIParamValue(flagOmitentityid)
			}
			if flagItemtype != "" {
				params["itemtype"] = formatCLIParamValue(flagItemtype)
			}
			if flagSubscriptions != "" {
				params["subscriptions"] = formatCLIParamValue(flagSubscriptions)
			}
			if flagQuery != "" {
				params["query"] = formatCLIParamValue(flagQuery)
			}
			if flagLimit != 0 {
				params["limit"] = formatCLIParamValue(flagLimit)
			}
			if flagStart != "" {
				params["start"] = formatCLIParamValue(flagStart)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "items", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Honor --limit when the API accepts but ignores ?limit=N.
			data = truncateJSONArray(data, flagLimit)
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagEntityid, "entityid", "", "")
	cmd.Flags().StringVar(&flagOmitentityid, "omitentityid", "", "")
	cmd.Flags().StringVar(&flagItemtype, "itemtype", "", "")
	cmd.Flags().StringVar(&flagSubscriptions, "subscriptions", "", "")
	cmd.Flags().StringVar(&flagQuery, "query", "", "")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "")
	cmd.Flags().StringVar(&flagStart, "start", "", "")

	return cmd
}
