// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newObjectivesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "objectives",
		Short:       "Learning objectives & progress",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newObjectivesCreateSetsCmd(flags))
	cmd.AddCommand(newObjectivesGetListCmd(flags))
	cmd.AddCommand(newObjectivesGetMapListCmd(flags))
	cmd.AddCommand(newObjectivesGetMasteryCmd(flags))
	cmd.AddCommand(newObjectivesGetMasteryDetailCmd(flags))
	cmd.AddCommand(newObjectivesGetMasterySummaryCmd(flags))
	cmd.AddCommand(newObjectivesGetSetCmd(flags))
	cmd.AddCommand(newObjectivesGetSubjectListCmd(flags))
	cmd.AddCommand(newObjectivesListSetsCmd(flags))
	cmd.AddCommand(newObjectivesPutCmd(flags))
	cmd.AddCommand(newObjectivesPutMapsCmd(flags))
	cmd.AddCommand(newObjectivesRestoreSetCmd(flags))
	cmd.AddCommand(newObjectivesUpdateSetsCmd(flags))
	return cmd
}
