// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPeergradingCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "peergrading",
		Short:       "Get and create peergrading",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPeergradingGetResponseCmd(flags))
	cmd.AddCommand(newPeergradingGetResponseInfoCmd(flags))
	cmd.AddCommand(newPeergradingGetResponseListCmd(flags))
	cmd.AddCommand(newPeergradingGetReviewListCmd(flags))
	cmd.AddCommand(newPeergradingPutResponseCmd(flags))
	return cmd
}
