// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// Hand-patched: putpeerresponse takes content as the raw body with ids in the
// query string (see buzz_rawput.go). Mirrors files put.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newPeergradingPutResponseCmd(flags *rootFlags) *cobra.Command {
	var pEnrollmentid, pItemid, pPeerid string
	var filePath, contentType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "put-response",
		Short:       "This command puts peer response data including comments, rubric score, and likert responses to the server.",
		Example:     "  agilix-buzz-pp-cli peergrading put-response --enrollmentid 123 --itemid abc --file review.json",
		Annotations: map[string]string{"pp:endpoint": "peergrading.put-response", "pp:method": "POST", "pp:path": "/cmd?cmd=putpeerresponse"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if pEnrollmentid == "" || pItemid == "" {
				_ = cmd.Usage()
				return usageErr(fmt.Errorf("--enrollmentid and --itemid are required"))
			}
			params := map[string]string{}
			putParam(params, "enrollmentid", pEnrollmentid)
			putParam(params, "itemid", pItemid)
			putParam(params, "peerid", pPeerid)
			return runRawContentPut(cmd, flags, "peergrading", "/cmd?cmd=putpeerresponse", params, filePath, stdinBody, contentType)
		},
	}
	cmd.Flags().StringVar(&pEnrollmentid, "enrollmentid", "", "Reviewer enrollment (required)")
	cmd.Flags().StringVar(&pItemid, "itemid", "", "Peer-graded activity item ID (required)")
	cmd.Flags().StringVar(&pPeerid, "peerid", "", "Enrollment ID of the peer being reviewed")
	cmd.Flags().StringVar(&filePath, "file", "", "Local file whose bytes are uploaded as the response content")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read raw response content from stdin")
	cmd.Flags().StringVar(&contentType, "contenttype", "", "Content-Type of the body (application/json, text/xml, or application/zip)")

	return cmd
}
