// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRatingsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "ratings",
		Short:       "Manage ratings command groups",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRatingsGetItemCmd(flags))
	cmd.AddCommand(newRatingsGetItemSummaryCmd(flags))
	cmd.AddCommand(newRatingsPutItemCmd(flags))
	return cmd
}
