// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRightsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "rights",
		Short:       "Rights & role assignments",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRightsCreateRoleCmd(flags))
	cmd.AddCommand(newRightsGetCmd(flags))
	cmd.AddCommand(newRightsGetActorCmd(flags))
	cmd.AddCommand(newRightsGetEffectiveCmd(flags))
	cmd.AddCommand(newRightsGetEffectiveSubscriptionListCmd(flags))
	cmd.AddCommand(newRightsGetEntityCmd(flags))
	cmd.AddCommand(newRightsGetEntitySubscriptionListCmd(flags))
	cmd.AddCommand(newRightsGetListCmd(flags))
	cmd.AddCommand(newRightsGetPersonasCmd(flags))
	cmd.AddCommand(newRightsGetRoleCmd(flags))
	cmd.AddCommand(newRightsGetSubscriptionListCmd(flags))
	cmd.AddCommand(newRightsListRolesCmd(flags))
	cmd.AddCommand(newRightsRestoreRoleCmd(flags))
	cmd.AddCommand(newRightsUpdateCmd(flags))
	cmd.AddCommand(newRightsUpdateRoleCmd(flags))
	cmd.AddCommand(newRightsUpdateSubscriptionsCmd(flags))
	return cmd
}
