// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSessionCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "session",
		Short:       "Authentication & session (login, token, proxy/login-as)",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSessionClearSecondFactorAuthenticationCmd(flags))
	cmd.AddCommand(newSessionCreateSecondFactorAuthenticationSecretCmd(flags))
	cmd.AddCommand(newSessionExtendSessionCmd(flags))
	cmd.AddCommand(newSessionFinishPasswordResetCmd(flags))
	cmd.AddCommand(newSessionForcePasswordChangeCmd(flags))
	cmd.AddCommand(newSessionGetKeyCmd(flags))
	cmd.AddCommand(newSessionGetPasswordLoginAttemptHistoryCmd(flags))
	cmd.AddCommand(newSessionGetPasswordQuestionCmd(flags))
	cmd.AddCommand(newSessionLoginCmd(flags))
	cmd.AddCommand(newSessionLogoutCmd(flags))
	cmd.AddCommand(newSessionProxyCmd(flags))
	cmd.AddCommand(newSessionPutKeyCmd(flags))
	cmd.AddCommand(newSessionResetLockoutCmd(flags))
	cmd.AddCommand(newSessionResetPasswordCmd(flags))
	cmd.AddCommand(newSessionSecondFactorAuthenticateCmd(flags))
	cmd.AddCommand(newSessionSetupSecondFactorAuthenticationCmd(flags))
	cmd.AddCommand(newSessionUnproxyCmd(flags))
	cmd.AddCommand(newSessionUpdatePasswordCmd(flags))
	cmd.AddCommand(newSessionUpdatePasswordQuestionAnswerCmd(flags))
	return cmd
}
