// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// Hand-patched: putstudentsubmission takes content as the raw body with ids in
// the query string (see buzz_rawput.go). Mirrors files put.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newSubmissionsPutStudentCmd(flags *rootFlags) *cobra.Command {
	var pEnrollmentid, pItemid, pRecordactivity string
	var filePath, contentType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "put-student",
		Short:       "This command puts a student submission for an activity to the server.",
		Example:     "  agilix-buzz-pp-cli submissions put-student --enrollmentid 123 --itemid abc --file answer.json",
		Annotations: map[string]string{"pp:endpoint": "submissions.put-student", "pp:method": "POST", "pp:path": "/cmd?cmd=putstudentsubmission"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if pEnrollmentid == "" || pItemid == "" {
				_ = cmd.Usage()
				return usageErr(fmt.Errorf("--enrollmentid and --itemid are required"))
			}
			params := map[string]string{}
			putParam(params, "enrollmentid", pEnrollmentid)
			putParam(params, "itemid", pItemid)
			putParam(params, "recordactivity", pRecordactivity)
			return runRawContentPut(cmd, flags, "submissions", "/cmd?cmd=putstudentsubmission", params, filePath, stdinBody, contentType)
		},
	}
	cmd.Flags().StringVar(&pEnrollmentid, "enrollmentid", "", "Student enrollment (required)")
	cmd.Flags().StringVar(&pItemid, "itemid", "", "Activity item ID (required)")
	cmd.Flags().StringVar(&pRecordactivity, "recordactivity", "", "true to record enrollment activity for this submission")
	cmd.Flags().StringVar(&filePath, "file", "", "Local file whose bytes are uploaded as the submission content")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read raw submission content from stdin")
	cmd.Flags().StringVar(&contentType, "contenttype", "", "Content-Type of the body (application/json, text/xml, or application/zip)")

	return cmd
}
