// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// Hand-patched: putworkinprogress takes content as the raw body with ids in the
// query string (see buzz_rawput.go). Mirrors files put. Note: --filepath is the
// DLAP query param naming the target path; --file is the local upload source.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newSubmissionsPutWorkInProgressCmd(flags *rootFlags) *cobra.Command {
	var pEnrollmentid, pItemid, pFilepath, pDisposition, pKeephistory string
	var filePath, contentType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "put-work-in-progress",
		Short:       "This command puts a work-in-progress file on the server in preparation for a student submission.",
		Example:     "  agilix-buzz-pp-cli submissions put-work-in-progress --enrollmentid 123 --itemid abc --filepath draft.docx --file draft.docx",
		Annotations: map[string]string{"pp:endpoint": "submissions.put-work-in-progress", "pp:method": "POST", "pp:path": "/cmd?cmd=putworkinprogress"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if pEnrollmentid == "" || pItemid == "" {
				_ = cmd.Usage()
				return usageErr(fmt.Errorf("--enrollmentid and --itemid are required"))
			}
			params := map[string]string{}
			putParam(params, "enrollmentid", pEnrollmentid)
			putParam(params, "itemid", pItemid)
			putParam(params, "filepath", pFilepath)
			putParam(params, "disposition", pDisposition)
			putParam(params, "keephistory", pKeephistory)
			return runRawContentPut(cmd, flags, "submissions", "/cmd?cmd=putworkinprogress", params, filePath, stdinBody, contentType)
		},
	}
	cmd.Flags().StringVar(&pEnrollmentid, "enrollmentid", "", "Student enrollment (required)")
	cmd.Flags().StringVar(&pItemid, "itemid", "", "Activity item ID (required)")
	cmd.Flags().StringVar(&pFilepath, "filepath", "", "Target path to store the work-in-progress file under")
	cmd.Flags().StringVar(&pDisposition, "disposition", "", "Disposition for the upload")
	cmd.Flags().StringVar(&pKeephistory, "keephistory", "", "true to keep prior versions")
	cmd.Flags().StringVar(&filePath, "file", "", "Local file whose bytes are uploaded as the content")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read raw content from stdin")
	cmd.Flags().StringVar(&contentType, "contenttype", "", "Content-Type of the uploaded content")

	return cmd
}
