// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSubmissionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "submissions",
		Short:       "Student submissions & responses",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSubmissionsGetScoDataCmd(flags))
	cmd.AddCommand(newSubmissionsGetStudentCmd(flags))
	cmd.AddCommand(newSubmissionsGetStudentHistoryCmd(flags))
	cmd.AddCommand(newSubmissionsGetStudentInfoCmd(flags))
	cmd.AddCommand(newSubmissionsGetTeacherResponseCmd(flags))
	cmd.AddCommand(newSubmissionsGetTeacherResponseInfoCmd(flags))
	cmd.AddCommand(newSubmissionsGetWorkInProgressCmd(flags))
	cmd.AddCommand(newSubmissionsPutItemActivityCmd(flags))
	cmd.AddCommand(newSubmissionsPutScoDataCmd(flags))
	cmd.AddCommand(newSubmissionsPutStudentCmd(flags))
	cmd.AddCommand(newSubmissionsPutTeacherResponseCmd(flags))
	cmd.AddCommand(newSubmissionsPutTeacherResponsesCmd(flags))
	cmd.AddCommand(newSubmissionsPutWorkInProgressCmd(flags))
	cmd.AddCommand(newSubmissionsSubmitWorkInProgressCmd(flags))
	return cmd
}
