// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// Hand-patched: putteacherresponse takes content as the raw body with ids in the
// query string (see buzz_rawput.go). Mirrors files put.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newSubmissionsPutTeacherResponseCmd(flags *rootFlags) *cobra.Command {
	var pEnrollmentid, pItemid, pZerounscored string
	var filePath, contentType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "put-teacher-response",
		Short:       "This command puts teacher response data including scores, comments, and grade status flags to the server.",
		Example:     "  agilix-buzz-pp-cli submissions put-teacher-response --enrollmentid 123 --itemid abc --file grade.json",
		Annotations: map[string]string{"pp:endpoint": "submissions.put-teacher-response", "pp:method": "POST", "pp:path": "/cmd?cmd=putteacherresponse"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if pEnrollmentid == "" || pItemid == "" {
				_ = cmd.Usage()
				return usageErr(fmt.Errorf("--enrollmentid and --itemid are required"))
			}
			params := map[string]string{}
			putParam(params, "enrollmentid", pEnrollmentid)
			putParam(params, "itemid", pItemid)
			putParam(params, "zerounscored", pZerounscored)
			return runRawContentPut(cmd, flags, "submissions", "/cmd?cmd=putteacherresponse", params, filePath, stdinBody, contentType)
		},
	}
	cmd.Flags().StringVar(&pEnrollmentid, "enrollmentid", "", "Student enrollment (required)")
	cmd.Flags().StringVar(&pItemid, "itemid", "", "Activity item ID (required)")
	cmd.Flags().StringVar(&pZerounscored, "zerounscored", "", "true to score unscored responses as zero")
	cmd.Flags().StringVar(&filePath, "file", "", "Local file whose bytes are uploaded as the response content")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read raw response content from stdin")
	cmd.Flags().StringVar(&contentType, "contenttype", "", "Content-Type of the body (application/json, text/xml, or application/zip)")

	return cmd
}
