// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSystemCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "system",
		Short:       "Server status & general utilities",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSystemGetCommandListCmd(flags))
	cmd.AddCommand(newSystemGetEntityTypeCmd(flags))
	cmd.AddCommand(newSystemGetStatusCmd(flags))
	cmd.AddCommand(newSystemSendMailCmd(flags))
	return cmd
}
