// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTokensCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "tokens",
		Short:       "Command tokens (delegated links)",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTokensCreateCommandCmd(flags))
	cmd.AddCommand(newTokensGetCommandCmd(flags))
	cmd.AddCommand(newTokensGetCommandInfoCmd(flags))
	cmd.AddCommand(newTokensListCommandCmd(flags))
	cmd.AddCommand(newTokensRedeemCommandCmd(flags))
	cmd.AddCommand(newTokensUpdateCommandCmd(flags))
	return cmd
}
