// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "users",
		Short:       "List, get, create, update, and verify users",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUsersCreateCmd(flags))
	cmd.AddCommand(newUsersGetCmd(flags))
	cmd.AddCommand(newUsersGetActiveCountCmd(flags))
	cmd.AddCommand(newUsersGetActivityCmd(flags))
	cmd.AddCommand(newUsersGetActivityStreamCmd(flags))
	cmd.AddCommand(newUsersGetDomainActivityCmd(flags))
	cmd.AddCommand(newUsersGetProfilePictureCmd(flags))
	cmd.AddCommand(newUsersListCmd(flags))
	cmd.AddCommand(newUsersRestoreCmd(flags))
	cmd.AddCommand(newUsersUpdateCmd(flags))
	cmd.AddCommand(newUsersVerifyEmailCmd(flags))
	return cmd
}
