// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newUsersGetDomainActivityCmd(flags *rootFlags) *cobra.Command {
	var flagDomainid string
	var flagStartdate string
	var flagEnddate string
	var flagMaxusers string
	var flagSelect string

	cmd := &cobra.Command{
		Use:         "get-domain-activity",
		Short:       "This command lists activity for all users in a specified domain.",
		Example:     "  agilix-buzz-pp-cli users get-domain-activity",
		Annotations: map[string]string{"pp:endpoint": "users.get-domain-activity", "pp:method": "GET", "pp:path": "/cmd?cmd=getdomainactivity", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/cmd?cmd=getdomainactivity"
			params := map[string]string{}
			if flagDomainid != "" {
				params["domainid"] = formatCLIParamValue(flagDomainid)
			}
			if flagStartdate != "" {
				params["startdate"] = formatCLIParamValue(flagStartdate)
			}
			if flagEnddate != "" {
				params["enddate"] = formatCLIParamValue(flagEnddate)
			}
			if flagMaxusers != "" {
				params["maxusers"] = formatCLIParamValue(flagMaxusers)
			}
			if flagSelect != "" {
				params["select"] = formatCLIParamValue(flagSelect)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "users", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagDomainid, "domainid", "", "")
	cmd.Flags().StringVar(&flagStartdate, "startdate", "", "")
	cmd.Flags().StringVar(&flagEnddate, "enddate", "", "")
	cmd.Flags().StringVar(&flagMaxusers, "maxusers", "", "")
	cmd.Flags().StringVar(&flagSelect, "select", "", "")

	return cmd
}
