// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// Hand-patched: putwikipage takes content as the raw body with ids in the query
// string (see buzz_rawput.go). Mirrors files put.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newWikisPutPageCmd(flags *rootFlags) *cobra.Command {
	var pEntityid, pItemid, pGroupid, pSlug string
	var filePath, contentType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "put-page",
		Short:       "This command puts a wiki page to the server.",
		Example:     "  agilix-buzz-pp-cli wikis put-page --entityid 123 --itemid abc --file page.txt",
		Annotations: map[string]string{"pp:endpoint": "wikis.put-page", "pp:method": "POST", "pp:path": "/cmd?cmd=putwikipage"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if pEntityid == "" || pItemid == "" {
				_ = cmd.Usage()
				return usageErr(fmt.Errorf("--entityid and --itemid are required"))
			}
			params := map[string]string{}
			putParam(params, "entityid", pEntityid)
			putParam(params, "itemid", pItemid)
			putParam(params, "groupid", pGroupid)
			putParam(params, "slug", pSlug)
			return runRawContentPut(cmd, flags, "wikis", "/cmd?cmd=putwikipage", params, filePath, stdinBody, contentType)
		},
	}
	cmd.Flags().StringVar(&pEntityid, "entityid", "", "Course/section that owns the wiki (required)")
	cmd.Flags().StringVar(&pItemid, "itemid", "", "Wiki item ID (required)")
	cmd.Flags().StringVar(&pGroupid, "groupid", "", "Group ID for group wikis")
	cmd.Flags().StringVar(&pSlug, "slug", "", "Wiki page slug")
	cmd.Flags().StringVar(&filePath, "file", "", "Local file whose bytes are uploaded as the page content")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read raw page content from stdin")
	cmd.Flags().StringVar(&contentType, "contenttype", "", "Content-Type of the body (default text/plain)")

	return cmd
}
