// Copyright 2026 RyanGravetteIDLA and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWikisCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "wikis",
		Short:       "List, get, create, and update wikis",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWikisCopyPagesCmd(flags))
	cmd.AddCommand(newWikisGetPageListCmd(flags))
	cmd.AddCommand(newWikisListRestorablePagesCmd(flags))
	cmd.AddCommand(newWikisPutPageCmd(flags))
	cmd.AddCommand(newWikisRestorePagesCmd(flags))
	cmd.AddCommand(newWikisUpdatePageViewedCmd(flags))
	return cmd
}
